### ISSUE TITLE
The COIN_INSTALL_DIR

### ISSUE THREAD

**Issue by kaarthiksundar** [coin-or/Dip#1]
Which is the install directory? Is it the directory where all the downloaded files were unzipped or is it the build directory that was created for installation?

**Comment by tkralphs** [comment]
It is the build directory (what `autoconf` calls the `prefix`), where files get installed when you do a `make install`. It should be the directory where you have subdirectories `bin/`, `include/`, `share/`, etc.

**Comment by kaarthiksundar** [comment]
Thanks, I was able to set up Dippy and try out small examples. I have a question regarding Dippy. I have a model for which I use DW decomposition and solve the problem using Dippy. Now I want to solve the same model without using Decomposition but using CPLEX MIP solver (Dippy by default uses CBC). I wanted to know if there is a way to set the solver to CPLEX using Dippy and solve the problem as a plain MIP.

**Comment by tkralphs** [comment]
As of 0.92.0, you can set up Dippy to use either Cbc, SYMPHONY, CPLEX, or Gurobi as the underlying MILP solver and the choice of solver is now a run-time dynamic choice. For example, here is the incantation to make all solvers available on our server at Lehigh.

```
../configure --with-gurobi-incdir=/usr/local/gurobi/linux64/include --with-gurobi-lib="-L/usr/local/gurobi/linux64/lib/ -lgurobi60 -lm -lpthread" --with-cplex-lib="-L/usr/local/cplex/lib/x86-64_linux/static_pic -lcplex -lpthread -lm" --with-cplex-incdir=/usr/local/cplex/include/ilcplex
```

Cbc and SYMPHONY are automatically available. After building, you switch solvers with the parameters `DecompIPSolver` and `DecompLPSolver`. 

Dip itself then has the option of solving the model directly with the underlying solver (with the parameter `doDirect`), although I haven't played with that capability in a while. That capability is not directly exposed in Dippy yet, although you can set the parameter and if the log level is high enough, you _should_ get the solution output (no guarantees). I don't think the solution will be available to you through the Python interface, though. I'm not sure how difficult it would be to make it available. It might take some work.

Another option, which might make more sense, is just to solve your Dippy model using PuLP, which already has a CPLEX interface. It might be a little hackish, but you could add all the constraints (master plus subproblem) to a PuLP model in (I think) exactly the same way as you do to Dippy, then solve the model using PuLP. If you give it a try, let me know how you make out.

Since Dippy is building PuLP model(s) underneath, it might not be difficult to just pass the DIP model to PuLP automagically to solve it using whatever solvers are available to PuLP. I will think about it.

**Comment by kaarthiksundar** [comment]
The generateCuts callback (DIP) and its Dippy mapping generate_cuts, as I understand, is equivalent to the UserCutCallback in CPLEX or Gurobi. I can add my separation routines in this callback (say separating an SEC from a TSP support graph). How do I add LazyConstraints i.e., how do I add constraints that remove, say sub-tours from an integer solution?

**Comment by tkralphs** [comment]
Lazy constraints, as they have come to be called, are really no different than any other cut---they are imposing structure that has been relaxed. What is different in the presence of "lazy constraints" like SECs is just that integrality of a solution to the current LP relaxation isn't enough to guarantee feasibility---the solution must also satisfy all lazy constraints. That's why DIP also has a callback (`DecompApp::APPisUserFeasible()`) for determining whether a given integer solution is actually feasible. If the solution is declared infeasible by the user, then a cut that separates that solution must be generated. If not, there will be no way to continue the algorithm and DIP will throw an exception. 

The Dippy wrapper for the feasibility check is `is_solution_feasible()`. Check [`tsp.py`](https://github.com/coin-or/Dip/blob/master/Dip/src/dippy/examples/tsp/tsp.py) to see how it's done in exactly the case you cited. I even have an enhanced version and an iPython notebook that solves the 50-city problem that was floating around the Internets a while back and displays the results on a Google map. I'm going to blog about Dip one of these days and use that as an example.

**Comment by kaarthiksundar** [comment]
Okay, I ve got the `is_solution_feasible()` working. As a next step, I want to perform just variable pricing i.e., again taking the example of a TSP, lets say I want to just consider just a few edge variables and dynamically generate variables with negative reduced cost and add it to the problem. This is just the plain pricing procedure without relaxing any constraints. Can this be achieved by not relaxing any constraints, adding the initial variables using `init_vars` and turning on the `doPriceCut` option in Dippy?

**Comment by tkralphs** [comment]
That is an interesting question! The approach you're talking about is something I played with a long time ago in my dissertation and it can actually be done natively in SYMPHONY (at least in principle---as far as i know, the option hasn't been used in more than decade). 

In DipPy, I think you can make it work in basically the way you're thinking, although there would be some overhead and I'm not sure if you would gain anything. In Dantzig-Wolfe, the solutions to the subproblem have to be in the space of solutions to the original problem and the columns of the master problem correspond to solutions to that subproblem. Solutions to the subproblem are combined to produce potential solutions to the original problem.

The space of variables in your original problem is the edges, so to make it work, you would have to return unit vectors as the solutions to your "subproblem" (i.e., your subproblem solutions would be a graph with a single edge). The solution to the original problem would then end up being a combination of these unit vectors, i.e., a combination of edges from the original graph.  The columns in your master would just be the columns from the original constraint matrix since you would just be multiplying the original constraint matrix by a unit vector.

Technically, since your subproblem would have no constraints (other than variable bounds and integrality), you could really return anything you want, but if you return non-trivial solutions, then you wouldn't be implementing  the method you're after. All in all, I don't see any reason this wouldn't work. As you say, it's really nothing more than having a box-constrained subproblem. Definitely do let me know how it goes if you try it.

**Comment by kaarthiksundar** [comment]
In all the param files in the examples folder, the doRelaxCut parameter line reads `(BROKEN)` in the end. What does this mean?

**Comment by kaarthiksundar** [comment]
I also have a follow up question regarding ``is_solution_feasible()``. I implemented the routine for TSP and have found that the solution contains sub tours. But the ``is_solution_feasible()`` returns only a true or false. How do I add the cut corresponding to the sub tour. I was under the impression that the ``generateCuts()`` would do that. But it does not seem to add the cuts and program runs in an infinite loop.

**Comment by tkralphs** [comment]
It just means that the Relax and Cut algorithm is not fully implemented.

**Comment by tkralphs** [comment]
@kaarthiksundar You had asked another question, which no longer seems to be here. I guess that means you figured it out?

**Comment by kaarthiksundar** [comment]
@tkralphs Yes, I had figured it out. Also I don't seem to understand what the logs say. Is there a place where this is documented? I looked at Galati's thesis hoping to find something there without much success.

**Comment by tkralphs** [comment]
There isn't much documentation. If you post questions here or on the mailing list, I will do my best to answer.

**Comment by kaarthiksundar** [comment]
I am having some issues running a basic branch-and-price code that I have written with Dippy. The files are https://gist.github.com/kaarthiksundar/934d2db96338d07dc38c (main.py) and https://gist.github.com/kaarthiksundar/fdb182b7bcde3416d526 (pickle file used by main.py). The problem seems to be that it gets stuck at ``Alps0250I Starting search...`` for more than an hour before I manually stop the execution. The problem size is very small (CPLEX can handle this directly within max 5 minutes without any decomposition).

**Comment by kaarthiksundar** [comment]
Log help required:

```
Processing Node   0 algo= PRICE_AND_CUT phase= PHASE_PRICE2 c=    0 p=  383 LB=  -4287.676 UB=     -4.200 nodeLB=   -160.681 gLB=   -160.681 gUB=        INF lpGap=      0.974 ipGap=        INF time=      29.40
```

What is difference between `nodeLB, gLB, gUB`. Also what is the `phase, c, p` in the log?

I am formulating a simple single machine scheduling problem. What I observe even for small instances if I set `doPriceCut = 1` is that the lpGap settles down at 0.974 (for this particular instance) and the algorithm does not seem to branch. Why is this behavior observed?

**Comment by tkralphs** [comment]
Unfortunately, the strings used to denote these various bounds are not really indicative of what they represent. I'll see if I can think of better strings to use. What's confusing when doing branch and price is that there are multiple bounds one has to consider, as opposed to the single bound one obtains by solving the LP relaxation in branch and cut. 

Here, `LB` and `UB` are the upper and lower bounds on the optimal value of the full relaxation associated with this particular node (what we would have if we knew all the columns). These bounds are obtained by solving the current restricted master.  Each time we solve the restricted master problem, the optimal solution value we obtain is an upper bound on the optimal value to the full relaxation. To get a _lower bound_ on the optimal value of the full relaxation, we have subtract the reduced cost of the column with most negative reduced cost with respect to the current master. We only obtain a good estimate of the actual lower bound yielded by the node `LB` and `UB` are close together, i.e., the most negative reduced cost column has a reduced cost near zero. If the reduced cost of the most negative reduced cost column is exactly zero, we have an exact value for the bound yielded by solving the relaxation in this node, but in practice, we won't get to exactly zero due to numerical inaccuracies and so-called `tailing off` effects.

To complicate matters, the sequence of `LB` values is not necessarily monotonic, so the current `LB` value may not actually be the best lower bound on the relaxation that we have seen so far. `nodeLB` is the best lower bound seen so far while processing this particular branch-and-bound node. `gLB` is the current global lower bound (the minimum node lower bound over all nodes). `gUB` is the global upper bound, which is the objective value of the best solution found so far. The algorithm as a whole terminates when `gLB` (approximately) equals `gUB`.

Phase has to do with two things: whether the algorithm is currently generating cuts or columns and whether it's in phase 1 (trying to obtain an initial feasible solution) or phase 2 (trying to improve the objective value). `PHASE_PRICE2` means that it's phase 2 and it's generating columns. `p` and `c represent the number of rounds of column generation (pricing) and cut generation (cutting) so far.

It's difficult to say exactly what's happening in this particular case without doing a bit more digging, but a few things are evident. First, `LB` and `UB` are not very close to each other, which means that the most negative reduced cost column generated in the last round had a reduced cost that wasn't anywhere close to zero. Thus, the column generation is still producing columns that appear to be important. On the other hand, the current lower bound is far from the best one seen so far, which means that you are probably experiencing some pretty severe fluctuations in the lower bound produced by the master in different iterations. This is a pretty well-known phenomena with column generation and is the motivation for the development of various stabilization techniques (_dual smoothing_ and _dual stabilization_ in the literature). It's caused be oscillations in the dual solutions being produced when solving the restricted master. Because we are using the simplex algorithm, we always get extremal solutions, which may exacerbate the problem. 

Since there have been 383 rounds of column generation and convergence doesn't seem to be anywhere in sight, it looks like you are in fact experiencing some pretty severe oscillations in the dual solution value. You could try just turning on DIP's dual smoothing, which is based on a simple technique of Wentges. The relevant parameter is `DualStab` and you can try just setting it to `True`. I haven't played around much with this, but it might work.

If this doesn't work, then there are other possibilities, but nothing has been implemented yet. If you are willing to share your instances, we can try to take a look and see what's happening.
