### ISSUE TITLE
Example data paths

### ISSUE THREAD

**Issue by spoorendonk** [coin-or/Dip#117]
The 'get_data.sh` scripts for many of the examples does not work, moved files, forbidden paths etc. For instance the MILPBlock example dataset.

**Comment by tkralphs** [comment]
Ugh, yeah, the files are still there, but some weird combination of changes on the server seems to trip up wget. I can go the URL in a browser and get the file, but with wget, I need to do

wget http://coral.ise.lehigh.edu/magh/decomp/atm.tgz

I will check with our sys admin because it would be nice if https access actually worked, which it seems not to at this point. But for now, this should fix at least that one case. Let me know if this does cover other cases.

**Comment by tkralphs** [comment]
Looking at this a bit closer, it appears that almost all the scripts had already been updated to point to

https://github.com/tkralphs/DecompLib

I fixed a few minor things in cf4f848a4987e3a4b606cf4c7c5c788c6262b638, but most of what was there seems to be working already. It may be easier just to clone the DecompLib repo, which I had forgotten I set up!
