### ISSUE TITLE
Building with MSVC

### ISSUE THREAD

**Issue by spoorendonk** [coin-or/Dip#128]
I am building using MSVC on Windows.

I am using coinbrew and basically following the steps in the `appveyor.yml` file. The main thing being
https://github.com/coin-or/Dip/blob/cf4f848a4987e3a4b606cf4c7c5c788c6262b638/appveyor.yml#L21-L24

However, it doesn't seem like coinbrew is using this setting for anything?
Everything is being build using MINGW and GCC and not MSBUILD as I expected.

It seems to be a common thing for the coin projects?

**Comment by tkralphs** [comment]
The main thing that --enable-msvc=MD does is change the compiler search order. It still needs to be able to find `cl` in the `PATH`. If it's not there, then it will still fall back to MinGW. So you probably need to run `vcvarsall.bat` before starting `bash`. Just follow the steps here: https://coin-or.github.io/user_introduction.html#building-with-visual-studio-in-msys2. You can check whether `cl` is in your path before doing the build with `which cl`.

**Comment by spoorendonk** [comment]
Ok got me a little further. Build is failing though. Checking my settings.

When I look at the appveyor build log for Visual Studio 2019 for `ARCH=win32-msvc16-md` it does look like it uses GCC.
https://ci.appveyor.com/project/tkralphs/dip-qk8he/builds/32548384/job/ujvqupai19q2gre6?fullLog=true

And if I open the bintray it is `.a` files. https://bintray.com/coin-or/download/download_file?file_path=Dip-master-win32-msvc16-md.zip

Am I mistaken?

**Comment by tkralphs** [comment]
You're right, thanks, I introduced a bug into appveyor.yml a while back. 

Take a look at this build, where things were working properly if you want to see what it should look like.

https://ci.appveyor.com/project/tkralphs/dip-qk8he/builds/32266770/job/h8aea59l4saixb8o

The problem is basically that I changed the strings for specifying the architecture, but forgot to change the corresponding `if` conditionals, so that `vcvarsall.bat` wasn't being run (same as what happened to you). I'll fix this later tonight.

By the way, one of these days, I will update to the new version of our build tools and that will change things pretty substantially. Well, not so much from a usage standpoint, but it be will possible to get real Windows DLLs. Depending on how your Python package is working, this may be important for you.

**Comment by spoorendonk** [comment]
If I follow the instructions at https://coin-or.github.io/user_introduction.html#building-with-visual-studio-in-msys2 it is set up correctly and I get

```sh
$ which link
/c/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/HostX64/x64/link
```

When looking at https://github.com/coin-or/Dip/blob/master/appveyor.yml
I do

```cmd
>"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
>C:\msys64\usr\bin\bash -lc "export PATH=\"C:\msys64\mingw64\bin\":$PATH; which link"
/usr/bin/link                                                                                             
```
Is this the bug you refer to? Also tried setting up the VS env inside bash, but that didn't work either.

Anyway, does running the configure script play well with MSVC?
I am adding https://sourceforge.net/projects/pthreads4w/ to get threading in CBC working. Should this be part of the build?
Right now I build the `Dip.sln` file directly with MSBUILD. After updating to `v16` and changing some paths it works. Is this something to support? It would mean updating `.vcxproj` files in all projects.

Looking forward to the new build system :). I am using [conan.io](https://conan.io) it could be an alternative to coinbrew.

**Comment by tkralphs** [comment]
The bug is fixed and everything is working fine on Appveyor right now (see, e.g., [here](https://ci.appveyor.com/project/tkralphs/dip-qk8he/build/job/hmg8drmus5g8wh7k?fullLog=true)). The bug was fixed in bcd924f5788, it was preventing `vcvarsall.bat` from being run. Now, `cl` is properly chosen as the compiler. It's not clear to me what's going wrong with your build. Could you be more specific? Where does it diverge from the appveyor run? Can you at least replicate that? It's important that you do things in exactly the order specified in the documentation, so that the right `link` command is invoked. You should **not** be using `/usr/bin/link`, but the MSVC one. You run `vcvarsall.bat` **after** adding the MSys2 directory to your path and then run `bash`. 

Yes, the configure script does play well with MSVC, we have put a lot of effort into making sure that's the case. And it will be even better with the newer build system. I have not tried to build Cbc with pthreads under MSVC, but yes, if we can get it to work, that would be great. I know others have done it. There is a page somewhere describing how to do it. 

In the past, I spent many, many hours trying to maintain the Visual Studio files. I lost my energy for that. It's a huge pain in the butt. I might be willing to just add what you've generated to all of the projects, but the problem is that it's very difficult to make sure that all the files committed are "clean" and don't have any settings that were tweaked just for the person that made the files. I think there should be working `.vcxproj` files for the Cbc stack already, no?

conan.io looks cool. I did actually look into some package managers before writing coinbrew. I don't remember if I saw that one or not (there are others out there), but I couldn't find anything that had the full range of capabilities I wanted. I'll take a look, but I guess now that coinbrew does almost all of what I want, I can't see abandoning it.

**Comment by tkralphs** [comment]
Hmm, conan.io looks nice, but also quite heavy. I wouldn't want to require installation of something that heavy that also depends on Python, etc. It also seems along the same lines as conda and homebrew. I've been trying to carve out some time to look into conda recipes, what is the advantage of this over conda? Especially if you are building Python packages, conda seems natural. By the way, I'm going to add the ability to install Python packages to coinbrew, e.g., build the dependencies, then install the Python package itself.

**Comment by spoorendonk** [comment]
I use conan.io for c++ only. It is nice for importing third party packages and building on mulitple platforms. I have no experience with conan for python. I would prefer conda or pypi for consuming python packages.

I am building a conan package for my other library to consume Dip and in that I use coinbrew to build. For Linux no problem. For windows I had trouble getting the command line stuff to work. When following the setup in appveyor by running

```cmd
set PATH=C:\msys64\usr\bin;%PATH%
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
``` 
and then
```cmd
C:\msys64\usr\bin\bash -lc "export PATH=\"C:\msys64\mingw64\bin\":$PATH; \coinbrew build Dip ...."
```
it uses gcc and
```cmd
C:\msys64\usr\bin\bash -lc "export PATH=\"C:\msys64\mingw64\bin\":$PATH; which link"
```
outputs `/usr/bin/link` which is wrong. But if I do
```cmd
bash
````
and then in the bash shell does
```bash
which link
```
I get the visual studio one.

Reverting to conans (MSBuild helper)[https://docs.conan.io/en/latest/reference/build_helpers/visual_studio.html] and using the Visual Studio project files worked perfectly. However, I too would prefer not to have to maintain project files.

Now I set CBC_THREAD define and OPENMP compile flag by hand to enable multi-threading. Are there other important flags I should know about?

**Comment by tkralphs** [comment]
Hmm, yeah, the `PATH` from Windows doesn't get passed in when you run a bash command using `bash -lc` instead of starting up a `bash` shell from the command line and running it inside the shell. This is what happens for me
```
C:\>set PATH=C:\msys64\usr\bin;%PATH%
C:\>bash -lc "echo $PATH"
/usr/local/bin:/usr/bin:/bin:/opt/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
```
For some reason, it seems to get the global `PATH` variable when running `bash -lc`, but gets the local `PATH` defined in the `cmd` shell when starting a new subshell. I guess because when running `bash -lc`, it's not actually starting a subshell. The behavior is different in Linux. I'm not entirely sure how to address this, but since I did actually want to create batch script like what you're suggesting that users could launch to build projects, I guess it's worth some proving. Some Googling is in order. I don't have any bandwidth for it this week, but next week. 

About `conda`, as I understand, the point of it is specifically to address the fact that a Python packages sometimes need to bring in dependencies that have to be built outside of Python. So it isn't actually mainly focused on Python (`pip` does fine for that), it is focused on just building separate dependencies, like Dip itself. You might take a look and see if it does what you need. There are already conda recipes for building the Cbc stack (quite a few actually) and these have nothing to do with Python, they're just building Cbc because it's needed for a Python package. See, e.g.,

https://github.com/wolfv/staged-recipes/tree/add_coin_or/recipes

**Comment by tkralphs** [comment]
More to the point
```
C:\>set PATH=C:\Blah;%PATH%
C:\>bash -lc "echo $PATH"
/usr/local/bin:/usr/bin:/bin:/opt/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
```

**Comment by tkralphs** [comment]
Actually, another thing is that you shouldn't need to add `C:\msys64\mingw64\bin\` to the `PATH` when using Visual Studio. I don't think that is done in Appveyor, if you look closely. Not adding that might be enough to make it work, since then gcc would then not be in the `PATH`. You could also trying adding `C:\msys64\usr\bin` to the _end_ of the `PATH` instead of the beginning. I guess it would still work.

**Comment by spoorendonk** [comment]
Success by modifying the path. When I put all the msys2 stuff in the end I get the right link and cl.

However, when running
```sh
./coinbrew build Dip --no-prompt --build=x86_64-w64-mingw32 --enable-msvc=MD --verbosity 4 --tests main --enable-relocatable --no-third-party
```

I get a lot of errors when compiling Cbc. Like:

```sh
libCbcSolver.lib(CbcSolver.obj) : error LNK2019: unresolved external symbol "public: void __cdecl CglGomory::passInOriginalSolver(class OsiSolverInterface *)" (?passInOriginalSolver@CglGomory@@QEAAXPEAVOsiSolverInterface@@@Z) referenced in function "int __cdecl CbcMain1(int,char const * * const,class CbcModel &,int (__cdecl*)(class CbcModel *,int),class CbcSolverUsefulData &)" (?CbcMain1@@YAHHQEAPEBDAEAVCbcModel@@P6AHPEAV1@H@ZAEAVCbcSolverUsefulData@@@Z)
```

It seems like Cbc cannot find the Cgl stuff? It seems somehow the paths for Cgl is not passed to Cbc? Any ideas where to look?

**Comment by tkralphs** [comment]
All is working well here:

https://ci.appveyor.com/project/tkralphs/dip-qk8he

Maybe compare your log to the one here:

https://ci.appveyor.com/project/tkralphs/dip-qk8he/build/job/c6u4few6lgjhnsa3?fullLog=true

and see if you can spot any differences. If you can't see anything obvious, then run coinbrew with `--verbosity 4` and attach the full output, as well as `config.log` from Dip here and I'll see what I can see. 

I still have on my TODO list to get Dip upgraded to the new build system, which should make things easier. I'll try hard to get to it in the next week or so if you are back to looking at this.

**Comment by spoorendonk** [comment]
OK. Finally nailed this. It took a lot of %PATH% tinkering on windows to get the correct msys2 tools to go into the configure script.
