### ISSUE TITLE
Use FICO Xpress as third party LP/IP solver

### ISSUE THREAD

**Issue by spoorendonk** [coin-or/Dip#129]
Add support for FICO Xpress

I am not an autotools champion. It seems like it may be straight forward by following the pattern for CPLEX and GUROBI support? What file to modify `configure.ac`?

I recall an issue somewhere on using `COIN_HAS_XXX` would this be relevant to address here?

**Comment by tkralphs** [comment]
This would be great, but I guess the modifications to the `configure` script are the eas(y|ier) part. Yes, following the pattern for CPLEX and Gurobi should work. Most likely, just adding
```
AC_COIN_CHECK_PACKAGE(Xpr, [osi-xpress], [DipLib])
```
is all you need, the heavy lifting is done by the `configure` script of `Osi`, which already has support for Xpress. The heard part is re-running the autotools in order to generate the `configure script itself. 

I can pretty easily do all this and push it if with some empty blocks for where you would need to add the calls to `OsiGrb`. Will try to do today. I'm trying to find some time to work on porting to the new BuildTools and cleaning up some other things, but haven't gotten there yet.

**Comment by spoorendonk** [comment]
That would be awesome. Then I can plug-in the `OsiXprSolverInterface` calls.

Out of curiosity. How to re-run autotools to generate `configue` script? Should the above line be added to `configure.ac`? and then `autoconf ?` something?

**Comment by tkralphs** [comment]
The gory details are here: https://github.com/coin-or-tools/BuildTools/wiki/pm-autotools. In a nutshell, you need to install the correct version of the autotools first: https://github.com/coin-or-tools/BuildTools/wiki/pm-get-autotools and then you just run the `run_autotools` script in the directory where `configure.ac` lives. It's not terribly difficult once you get the tools installed, but the required versions are pretty old (this is for the old version of the autotools, which is going away).

**Comment by spoorendonk** [comment]
So if I want to this on the Dip master branch should I get BuildTools also? It is removed as a dependency. Or what is the new way of doing this?

**Comment by spoorendonk** [comment]
It seems that the OsiXpr interface is outdated. Some stuff needs to be implemented.
Should this be done on Osi `master` and then cherry-picked to `stable`? Or what would be the procedure?

**Comment by spoorendonk** [comment]
Also there is a lot of solver specific stuff for cplex, gurobi, cbc and symphony that probably should be handled in Osi also?

**Comment by spoorendonk** [comment]
And the `DIP_HAS_XXX` should be changed to `COIN_HAS_XXX`

**Comment by spoorendonk** [comment]
The build system is updated for the dependencies (Osi) so `coinbrew` flags

`--with-xpress-incdir="/opt/xpressmp/include/" --with-xpress-lib="-L/opt/xpressmp/lib/ -lxprs"`

are now

`--with-xpress-cflags="-I/opt/xpressmp/include/" --with-xpress-lflags="-L/opt/xpressmp/lib/ -lxprs" --with-express`

for the deps.

How to update Dip build system? Is it the head og BuildTools?

**Comment by tkralphs** [comment]
OK, sorry for the delay, I actually did most of this last night, but then got distracted and didn't push it. I just pushed a new branch `add_express_support` that you can build off of. I believe that all the changes needed in the build system are there and I put in stubs in all the places I think you will need to add code. I believe it should build right now as it is, but I didn't try building it for now, since I guess you will be modifying it further anyway, and this should be a good starting point. 

To answer some of your questions,

- Yes, there is a lot of code for each solver specifically. We started out long ago trying to do everything from Osi and not to have much solver-specific code, but over time, more and more solver-specific crept in form various reasons. If you see things that can be pulled back up to the level of Osi, that's great. The ultimate goal would be to do that as much as possible. One big change I made a while back that resulted in some of this is to allow run-time switching of solvers. It used to be compile-time. This makes s difference in how the solvers are called, as you will see. Also, switching away from OsiCbc was another change (for the reasons you know).
- The current master of Dip depends on the stables of other projects because of what I was explaining previously about the migration. So you really need to build Dip master against Osi 0.108 currently. Once the Dip build system is migrated (I will try to do it soon), then we can build against Osi master and the flags will be as you indicated. For now, the flags should be the old ones and you should build only with Osi stable. 
- I did not change DIP_HAD_XXX to COIN_HAS_XXX for now, since this is a bit more involved than it appears and I'm not sure that it's the right thing to do in the old build system. Was there an issue open about that, as you remember? Can you point to it?
- For update OsiXpress, you can do it in master and we'll cheery pick over to stable. That is the current workflow. I thought it was up to date, though. 

OK, that should get you going for now.

**Comment by spoorendonk** [comment]
Thanks. I will merge what I need.

> * I did not change DIP_HAD_XXX to COIN_HAS_XXX for now, since this is a bit more involved than it appears and I'm not sure that it's the right thing to do in the old build system. Was there an issue open about that, as you remember? Can you point to it?

Can't recall. Maybe I got it wrong. I will leave it for now.

**Comment by spoorendonk** [comment]
I merged your makefile/configure changes into my branch and reran the autotools.

I am building against Osi stable/0.108 where I am modifying OsiXpr at the moment (to goto Osi master).

I still have some build issues. At the moment I do

```sh
/coinbrew build Dip --enable-debug --no-prompt --with-xpr-lib="-L/opt/xpressmp/lib/ -lxprs -lOsiXpr" --with-xpr-incdir="/opt/xpressmp/include"  --with-xpress-lib="-L/opt/xpressmp/lib/ -lxprs" --with-xpress-incdir="/opt/xpressmp/include" --tests=none
```

because `--with-xpr-*` is needed in Dip and `--with-xpress-*` is needed in Osi stable. Also I need to add the `-lOsiXpr` as a linker flag for Dip. Not sure why it does not pick up automatically?

I skip the tests because OsiXpr fails the Osi tests. I did some fixes but the tests still fails for dual rays unless one actively disables presolve and resolves the lp inside the `getDualRay`. Which I think is the wrong way around it.

When hooking Xpress up in Dip I get a bunch of memory errors. I am not sure why yet. I am not too familiar with the Xpress C interface so there may be some assumptions not there yet. I tried bypass the inner OsiXpr caching but still get errors.

Another thing I stumbled upon. It seems that the default LP algorithm is dual simplex, even when doing column generation. Should the `SolveMasterUpdateAlgo` not default to `DecompPrimSimplex` in that case? Am I missing something?

**Comment by spoorendonk** [comment]
My Osi branch https://github.com/spoorendonk/Osi/tree/osixpr-update

**Comment by spoorendonk** [comment]
made a PR on Osi https://github.com/coin-or/Osi/pull/140 for changes and cherry picked to stable in https://github.com/coin-or/Osi/pull/141

**Comment by tkralphs** [comment]
Hmm, regarding `--with-xpr-*` versus `--with-xpress`, that can be fixed by spelling out the firs argument in the same way in `configure.ac` here:
```
AC_COIN_CHECK_PACKAGE(Cpx,  [osi-cplex],  [DipLib])
AC_COIN_CHECK_PACKAGE(SYMPHONY, [osi-sym], [DipLib])
AC_COIN_CHECK_PACKAGE(Grb, [osi-gurobi], [DipLib])
AC_COIN_CHECK_PACKAGE(Xpr, [osi-xpress], [DipLib])
```
but I don't think you should need to provide any argument for Dip. It should find the library through the `.pc` file generated by Osi (`osi-xpress.pc`). Did you try leaving out --with-xpr* when building? 

As far as primal versus dual simplex, yes, you would think primal would make more sense with column generation, but since Dip can also generate cuts while doing column generation, I guess it's not that obvious what would be the most advantageous. We can do some empirical testing once we get things cleaned up a bit.

Have you taken care of the other issues you raised above? I'm trying to get Xpress installed now. What platform are you on?

**Comment by spoorendonk** [comment]
I am on Linux. Need to test also on Windows.

Test runs with Xpress, so I am trying trying out different build lines command to clean it up.

**Comment by tkralphs** [comment]
I don't mind changing the strings as I indicated above to match Osi if necessary. But at least with Cplex, I didn't run into the issue your're raising and the strings are different there, too. It would be nice not to change things mid-stream in stable. But when I get to updating DIP to the new build system, we can make everything match and that should fix the issue for you, since you'll then switch to using the new version I guess.

**Comment by spoorendonk** [comment]
I got it working with

```sh
./coinbrew build Dip --no-prompt --with-xpress-lib="-L/opt/xpressmp/lib/ -lxprs" --with-xpress-incdir="/opt/xpressmp/include" --verbosity 2 --tests=none
```

If I use the `--with-xpr-*` flags for Dip then OsiXpr is not build by Osi and then not found by Dip. Something to do with https://github.com/coin-or/Osi/blob/17b9edf1bac18b22c217e892b9d85810132f70c1/Osi/configure.ac#L76 
and/or  
https://github.com/coin-or/Osi/blob/17b9edf1bac18b22c217e892b9d85810132f70c1/Osi/configure.ac#L109 ?

Won't there be the same issue with Cpx/Cplex, Grb/Gurobi?

Changing the string in Dip to Xpress results in a lot defines being named `COIN_HAS_XPRESS` but it is still `COIN_HAS_XPR` from Osi. 

So maybe better to leave it as Xpr for now and then have this workaround for compiling until the new build system is in place?

Also I need the `--tests=none` because Osi fails on the OsiXpr tests right now. Need to look into that also at some point.

**Comment by tkralphs** [comment]
Yes, right, it's a little confusing, but you only need the flags that Osi expects (as long as you have `pkg-config` on your system). What should then happen is that Osi finds the Xpress library and will build OsiXpr, finally installing the file `osi-xpress.pc`. What Dip is then looking for is actually the OsiXpr package, not the Xpress library itself (the Xpress library will be linked in as a dependency of OsiXpr). So as long as pkg-config is present to find the `.pc` file, the Dip arguments to configure are not needed. If they were to be needed, they would actually be specifying where the OsiXpr library itself lives (and then also the Xpress library, as a dependency). 

As for the inconsistency between the configure option `--with-xpress` and the internal flag `COIN_HAS_XPR`, that is more or less hard-wired into the old version of the build tools, per the documentation here: https://github.com/coin-or-tools/BuildTools/blob/stable/0.8/coin.m4#L2670 But we don't actually need to look at the symbols defined in Osi (there is a long story around these `COIN_HAS_*` symbols, they are duplicated in different projects and this can cause issues---this has been cleaned up a bit in the new version).

**Comment by spoorendonk** [comment]
Then I guess all is good with xpress stuff for now.

Do you want to wait the memory bug to be fixed or should that be handled as a separate issue?
Otherwise I would appreciate a cherry pick these changes to stable also.

**Comment by tkralphs** [comment]
Since the bug doesn't seem to be related to these changes, I don't feel the need to wait. I can merge and cherry pick. I did just now find that that the current unit test is failing in stable with CPLEX in pretty egregiously, which seems to indicate an issue with DIP itself. I'll try to find some time to debug it, but if you have any bandwidth, I can tell you how to replicate.

**Comment by spoorendonk** [comment]
I don't have access to CPLEX. But if it can be replicated with Xpress, Cbc, SYMPHONY than I can have a look. Should we move discussion to a new issue?

**Comment by tkralphs** [comment]
Sure, yeah, I was going to file a new issue to remind me about it. I just merged your PRs and then merged `master` over to `stable/0.95`.

**Comment by spoorendonk** [comment]
Thanks

**Comment by spoorendonk** [comment]
@tkralphs I guess branch https://github.com/coin-or/Dip/tree/add_express_support can be deleted

Seems like you merged `master` into `stable\0.95` before the Xpress stuff was added?

**Comment by tkralphs** [comment]
Ugh, yes, will fix.

**Comment by tkralphs** [comment]
I just force pushed a new merge commit. Hopefully, that doesn't cause any problems.
