### ISSUE TITLE
Typo DecompMain

### ISSUE THREAD

**Issue by Efsilvaa** [coin-or/Dip#2]
Hi,
I am afraid there is a typo in DecompMain.cpp, lines 583 to 585, stopping the build in MSVC.

"SYMPONY"  --> SYMPHONY
#ifdef DIP_HAS_CLP --> #ifdef DIP_HAS_SYM  

By the way, the nice work!
Eduardo

**Comment by tkralphs** [comment]
@Efsilvaa You're correct about the typos (see 5816b4ac56192f01fc0a851aa6ea16e48c578f5b), but I guess this won't fix the Visual Studio build. If you're trying to build with the solution files, they may be broken due to changes in the symbols that would need to be defined manually to make everything work. My guess is that you need to add the symbols 

```
DIP_HAS_SYMPHONY
DIP_HAS_CLP
DIP_HAS_CBC
```

to the lists of preprocessor defines on, e.g., this line of the project file:

https://github.com/coin-or/Dip/blob/master/Dip/MSVisualStudio/v10/Decomp/Dip.vcxproj#L86

If you do get it patched up, feel free to send a pull request. Otherwise, i will try also to get to it and test it. 

By the way, the easiest way to build with the Visual Studio compiler, by the way, is with the autotools using Msys2. See, e.g., this [Appveyor build](https://ci.appveyor.com/project/tkralphs/dip/build/1.0.66/job/eera6kopdr2k3u6o). Basic instructions on how to build with MSys2 are similar to the ones [here](https://projects.coin-or.org/SYMPHONY/wiki/BuildAndInstall#BUILDINGWITHMSys2orCYGWIN) for SYMPHONY.

**Comment by tkralphs** [comment]
Ah, OK, I actually see now what you meant. I guess the fix I already put in did fix the problem, so I'm closing this issue.

**Comment by Efsilvaa** [comment]
Thanks Ted for the tips.

I will try them.

Eduardo

---

Eduardo F. Silva
